### ISSUE TITLE
tracer/disable: No such file or directory

### ISSUE THREAD

**Issue by yxxxqqq** [tensorlayer/hyperpose#277] opened 2020-06-12 03:10 UTC
I got this error when I compile this repo. 
'trace.hpp:10:10: fatal error:tracer/disable: No such file or directory'

**Comment by lgarithm** [comment] 2020-06-15 07:08
Could you try rebuild after remove the `3rdparty` folder?
It might be caused by a cmake issue not updating already cloned external project.

**Comment by ganler** [comment] 2020-06-15 07:11
Hi this is a problem of not successfully downloading the 3rdparties using cmake.

This may help if your OS is Ubuntu:

0. re-clone our repo from master.
1. pip3 install make # The make package from pypi is of very new version
2. mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release # Make sure you are using the cmake from pypi. You can use `where cmake` to find its location like `$HOME/.local/bin/cmake`
3. make

Let me know if this works and also follow @lgarithm 's instructions. Thank U.

**Comment by yxxxqqq** [comment] 2020-06-15 10:35
I  cloned the project again, and it works now. thank you very much!

**Comment by ganler** [comment] 2020-06-15 14:05
Closed as this issue has been solved.

**Closed by ganler** 2020-06-15 14:05 UTC

**Comment by ConnorM17** [comment] 2020-06-25 16:53
I am having this same issue during make, "In file included from /media/agx1/agxSSD/hyperpose/src/trace.cpp:1:0:
/media/agx1/agxSSD/hyperpose/src/trace.hpp:10:10: fatal error: tracer/disable: No such file or directory
 #include <tracer/disable>"

I tried following the steps Ganler posted above but no luck. Platform is Jetson AGX with JetPack 4.4.

```
agx1@agx1:/media/agx1/agxSSD/hyperpose/build$ /home/agx1/.local/bin/cmake .. -DCMAKE_BUILD_TYPE=RELEASE
BUILD_LIB ON
Using CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.0
-- Found CUDA: /usr/local/cuda-10.0 (found suitable exact version "10.0") 
-- [HyperPose] Examples Building Enabled.
-- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/gen_serialized_engine.example.cpp
-- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/operator_api_batched_images_paf.example.cpp
-- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/operator_api_batched_images_pose_proposal.example.cpp
-- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/operator_api_imshow_paf.example.cpp
-- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/operator_api_video_paf.example.cpp
-- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/operator_api_video_pose_proposal.example.cpp
-- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/stream_api_video_paf.example.cpp
-- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/stream_api_video_pose_proposal.example.cpp
-- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/tutorial/minimum_operator_api_video.example.cpp
-- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/tutorial/minimum_stream_api_video.example.cpp
-- [HyperPose] User Codes Building Enabled.
-- [HyperPose] Tests Building Enabled.
-- >>> [TEST] TO BUILD /media/agx1/agxSSD/hyperpose/examples/tests/thread_pool.test.cpp
-- >>> [TEST] TO BUILD /media/agx1/agxSSD/hyperpose/examples/tests/thread_safe_queue.test.cpp
-- >>> [TEST] TO BUILD /media/agx1/agxSSD/hyperpose/examples/tests/version.test.cpp
-- Configuring done
-- Generating done
-- Build files have been written to: /media/agx1/agxSSD/hyperpose/build
```
```
agx1@agx1:/media/agx1/agxSSD/hyperpose/build$ make
[  1%] Linking CXX executable test.version
[  5%] Built target test.version
[  6%] Linking CXX executable test.thread_safe_queue
[ 10%] Built target test.thread_safe_queue
[ 12%] Building CXX object CMakeFiles/stdtracer.dir/src/trace.cpp.o
In file included from /media/agx1/agxSSD/hyperpose/src/trace.cpp:1:0:
/media/agx1/agxSSD/hyperpose/src/trace.hpp:10:10: fatal error: tracer/disable: No such file or directory
 #include <tracer/disable>
          ^~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/stdtracer.dir/build.make:82: recipe for target 'CMakeFiles/stdtracer.dir/src/trace.cpp.o' failed
make[2]: *** [CMakeFiles/stdtracer.dir/src/trace.cpp.o] Error 1
CMakeFiles/Makefile2:184: recipe for target 'CMakeFiles/stdtracer.dir/all' failed
make[1]: *** [CMakeFiles/stdtracer.dir/all] Error 2
Makefile:114: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ganler** [comment] 2020-06-25 17:16
> I am having this same issue during make, "In file included from /media/agx1/agxSSD/hyperpose/src/trace.cpp:1:0:
> /media/agx1/agxSSD/hyperpose/src/trace.hpp:10:10: fatal error: tracer/disable: No such file or directory
> #include <tracer/disable>"
> 
> I tried following the steps Ganler posted above but no luck. Platform is Jetson AGX with JetPack 4.4.
> 
> ```
> agx1@agx1:/media/agx1/agxSSD/hyperpose/build$ /home/agx1/.local/bin/cmake .. -DCMAKE_BUILD_TYPE=RELEASE
> BUILD_LIB ON
> Using CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.0
> -- Found CUDA: /usr/local/cuda-10.0 (found suitable exact version "10.0") 
> -- [HyperPose] Examples Building Enabled.
> -- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/gen_serialized_engine.example.cpp
> -- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/operator_api_batched_images_paf.example.cpp
> -- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/operator_api_batched_images_pose_proposal.example.cpp
> -- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/operator_api_imshow_paf.example.cpp
> -- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/operator_api_video_paf.example.cpp
> -- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/operator_api_video_pose_proposal.example.cpp
> -- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/stream_api_video_paf.example.cpp
> -- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/stream_api_video_pose_proposal.example.cpp
> -- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/tutorial/minimum_operator_api_video.example.cpp
> -- >>> [EXAMPLE] TO BUILD /media/agx1/agxSSD/hyperpose/examples/tutorial/minimum_stream_api_video.example.cpp
> -- [HyperPose] User Codes Building Enabled.
> -- [HyperPose] Tests Building Enabled.
> -- >>> [TEST] TO BUILD /media/agx1/agxSSD/hyperpose/examples/tests/thread_pool.test.cpp
> -- >>> [TEST] TO BUILD /media/agx1/agxSSD/hyperpose/examples/tests/thread_safe_queue.test.cpp
> -- >>> [TEST] TO BUILD /media/agx1/agxSSD/hyperpose/examples/tests/version.test.cpp
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /media/agx1/agxSSD/hyperpose/build
> ```
> 
> ```
> agx1@agx1:/media/agx1/agxSSD/hyperpose/build$ make
> [  1%] Linking CXX executable test.version
> [  5%] Built target test.version
> [  6%] Linking CXX executable test.thread_safe_queue
> [ 10%] Built target test.thread_safe_queue
> [ 12%] Building CXX object CMakeFiles/stdtracer.dir/src/trace.cpp.o
> In file included from /media/agx1/agxSSD/hyperpose/src/trace.cpp:1:0:
> /media/agx1/agxSSD/hyperpose/src/trace.hpp:10:10: fatal error: tracer/disable: No such file or directory
>  #include <tracer/disable>
>           ^~~~~~~~~~~~~~~~
> compilation terminated.
> CMakeFiles/stdtracer.dir/build.make:82: recipe for target 'CMakeFiles/stdtracer.dir/src/trace.cpp.o' failed
> make[2]: *** [CMakeFiles/stdtracer.dir/src/trace.cpp.o] Error 1
> CMakeFiles/Makefile2:184: recipe for target 'CMakeFiles/stdtracer.dir/all' failed
> make[1]: *** [CMakeFiles/stdtracer.dir/all] Error 2
> Makefile:114: recipe for target 'all' failed
> make: *** [all] Error 2
> ```

Hi @ConnorM17 

This is because you did not have the 3rdparty library(stdtracer, which is developed by @lgarithm ) installed successfully. This may be caused by the network or cmake execution. 

Can you find the source files of stdtracer in your project? 

In the worst case, you can try the following dirty tricks to make it run:

- Comment everything in `src/trace.hpp` and `src/trace.cpp`.
- Add `#define TRACE_SCOPE` in `src/trace.hpp`.

**Comment by ConnorM17** [comment] 2020-06-25 17:35
In my src directory of hyperpose I see trace.cpp and trace.hpp. I commented out everything in src/trace.hpp and src/trace.cpp, and then added `#define TRACE_SCOPE in src/trace.hpp`. This seems to have worked.

**Comment by ganler** [comment] 2020-06-25 18:32
> In my src directory of hyperpose I see trace.cpp and trace.hpp. I commented out everything in src/trace.hpp and src/trace.cpp, and then added `#define TRACE_SCOPE in src/trace.hpp`. This seems to have worked.

I mean the `stdtracer` source files in the `3rdparty` directory. Could you check it again? Thx.

**Comment by ConnorM17** [comment] 2020-07-06 20:00
Sorry. Yes, I do seem to have the souce files for stdtracer in the 3rdparty directory.
